// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Summeet.Api.Common.DataAccess;

#nullable disable

namespace Summeet.Api.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20241120183328_Asset")]
    partial class Asset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Summeet.Api.Common.DataAccess.Entities.Asset", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Summeet.Api.Common.DataAccess.Entities.AssetVariant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.HasKey("Key", "Color");

                    b.ToTable("AssetVariant", (string)null);
                });

            modelBuilder.Entity("Summeet.Api.Common.DataAccess.Entities.AssetVariant", b =>
                {
                    b.HasOne("Summeet.Api.Common.DataAccess.Entities.Asset", "Asset")
                        .WithMany("Variants")
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Summeet.Api.Common.DataAccess.Entities.Asset", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
